from __future__ import annotations

from typing import Any

from .provider import OpenAICompatibleProvider, ProviderError


SYSTEM_PROMPT = """You are RoboLab Core, an engineering assistant for safe educational robotics and embedded systems.
Return ONLY a JSON object with these keys:
summary: string
architecture: array of strings
components: array of strings
connections: array of strings
firmware: string
validation: array of objects with ok:boolean, name:string, details:string

Requirements:
- Be explicit about assumptions.
- Prefer commonly available development boards and modules unless the user specifies hardware.
- Do not claim code compiled, hardware was tested, or a circuit was electrically verified unless actual tool evidence is provided.
- Reject or gate dangerous high-voltage, weapon, explosive, or harmful-device requests.
- Include power/current/voltage concerns in validation when motors, servos, relays, batteries, or external supplies are involved.
- Firmware must be complete enough to be a useful starting implementation when the requested board and behavior are sufficiently specified.
"""


class EngineeringOrchestrator:
    def __init__(self, provider: OpenAICompatibleProvider | None = None) -> None:
        self.provider = provider or OpenAICompatibleProvider()

    async def generate(self, prompt: str) -> dict[str, Any]:
        prompt = prompt.strip()
        if len(prompt) < 12:
            raise ValueError("Prompt is too short")

        blocked = self._risk_gate(prompt)
        if blocked:
            return {
                "summary": "This project needs additional safety review before RoboLab can generate hardware instructions.",
                "architecture": [],
                "components": [],
                "connections": [],
                "firmware": "",
                "validation": [
                    {
                        "ok": False,
                        "name": "Safety gate",
                        "details": blocked,
                    }
                ],
                "source": "safety-gate",
            }

        try:
            draft = await self.provider.generate_json(
                system=SYSTEM_PROMPT,
                user=f"Design this project:\n\n{prompt}",
            )
            result = self._normalize(draft)
            result["source"] = "ai-provider"
            result["validation"] = self._augment_validation(prompt, result)
            return result
        except ProviderError as exc:
            return self._provider_unavailable(str(exc))

    @staticmethod
    def _risk_gate(prompt: str) -> str | None:
        text = prompt.lower()
        risky_terms = {
            "mains voltage": "Mains-voltage projects require qualified supervision and are not generated by this beta pipeline.",
            "high voltage": "High-voltage projects require additional expert safety review.",
            "explosive": "RoboLab does not generate explosive-device instructions.",
            "weapon": "RoboLab does not generate weapon-building instructions.",
        }
        for term, message in risky_terms.items():
            if term in text:
                return message
        return None

    @staticmethod
    def _normalize(data: dict[str, Any]) -> dict[str, Any]:
        def string_list(key: str) -> list[str]:
            raw = data.get(key, [])
            return [str(item).strip() for item in raw if str(item).strip()] if isinstance(raw, list) else []

        validation = data.get("validation", [])
        normalized_validation: list[dict[str, Any]] = []
        if isinstance(validation, list):
            for item in validation:
                if isinstance(item, dict):
                    normalized_validation.append(
                        {
                            "ok": bool(item.get("ok", False)),
                            "name": str(item.get("name", "Check")),
                            "details": str(item.get("details", "")),
                        }
                    )

        return {
            "summary": str(data.get("summary", "")),
            "architecture": string_list("architecture"),
            "components": string_list("components"),
            "connections": string_list("connections"),
            "firmware": str(data.get("firmware", "")),
            "validation": normalized_validation,
        }

    @staticmethod
    def _augment_validation(prompt: str, result: dict[str, Any]) -> list[dict[str, Any]]:
        checks = list(result.get("validation", []))
        text = prompt.lower()
        power_sensitive = any(term in text for term in ("motor", "servo", "relay", "battery", "pump"))

        checks.append(
            {
                "ok": bool(result.get("components")),
                "name": "Component coverage",
                "details": f"{len(result.get('components', []))} component entries returned.",
            }
        )
        checks.append(
            {
                "ok": bool(result.get("firmware", "").strip()),
                "name": "Firmware presence",
                "details": "Firmware output is present." if result.get("firmware", "").strip() else "No firmware was returned.",
            }
        )
        if power_sensitive:
            power_mentioned = any(
                token in " ".join(result.get("connections", [])).lower()
                for token in ("power", "supply", "current", "voltage", "ground")
            )
            checks.append(
                {
                    "ok": power_mentioned,
                    "name": "Power-path review",
                    "details": "Power considerations are represented in the generated connection plan."
                    if power_mentioned
                    else "Motor/servo/relay/battery projects must explicitly cover supply voltage, current and grounding.",
                }
            )
        return checks

    @staticmethod
    def _provider_unavailable(reason: str) -> dict[str, Any]:
        return {
            "summary": "The RoboLab backend is running, but no usable AI provider is configured yet.",
            "architecture": [],
            "components": [],
            "connections": [],
            "firmware": "",
            "validation": [
                {
                    "ok": False,
                    "name": "AI provider",
                    "details": reason,
                }
            ],
            "source": "backend-no-provider",
        }
